/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:          'var(--color-bg)',
        bg1:         'var(--color-bg-1)',
        surface:     'var(--color-surface)',
        surfaceHover:'var(--color-surface-hover)',
        surfaceSolid:'var(--color-surface-solid)',
        panel:       'var(--color-panel)',
        border:      'var(--color-border)',
        glassBorder: 'var(--color-glass-border)',
        borderGlow:  'var(--color-border-glow)',
        borderHi:    'var(--color-border-hi)',
        text:        'var(--color-text)',
        textDim:     'var(--color-text-dim)',
        muted:       'var(--color-muted)',
        primary:     'var(--color-primary)',
        primaryDark: 'var(--color-primary-dark)',
        secondary:   'var(--color-secondary)',
        accent:      'var(--color-accent)',
        glow:        'var(--color-glow)',
        glowDim:     'var(--color-glow-dim)',
        success:     'var(--color-success)',
        warning:     'var(--color-warning)',
        danger:      'var(--color-danger)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
      },
      boxShadow: {
        'glow':           '0 0 32px -6px var(--color-glow)',
        'glow-lg':        '0 0 60px -8px var(--color-glow)',
        'glow-xl':        '0 0 100px -12px var(--color-glow)',
        'glow-primary':   '0 0 28px -6px var(--color-primary)',
        'glow-primary-lg':'0 0 60px -8px var(--color-primary)',
        'glow-success':   '0 0 20px -6px var(--color-success)',
        'glow-danger':    '0 0 20px -6px var(--color-danger)',
        'inner-glow':     'inset 0 0 20px rgba(0, 212, 255, 0.06)',
        'card':           '0 4px 24px rgba(0, 0, 0, 0.4), 0 1px 2px rgba(0,0,0,0.2)',
        'card-hover':     '0 8px 40px rgba(0, 0, 0, 0.5), 0 2px 8px rgba(0,0,0,0.3)',
        'toast':          '0 16px 48px rgba(0, 0, 0, 0.6)',
      },
      backdropBlur: {
        xs:  '2px',
        sm:  '6px',
        md:  '12px',
        lg:  '20px',
        xl:  '28px',
        '2xl':'40px',
      },
      animation: {
        'drift':        'drift 20s ease-in-out infinite',
        'drift-alt':    'drift-alt 24s ease-in-out infinite',
        'spin-slow':    'spin-slow 14s linear infinite',
        'spin-reverse': 'spin-reverse 18s linear infinite',
        'float':        'float 5s ease-in-out infinite',
        'glow-pulse':   'glow-pulse 2.5s ease-in-out infinite',
        'shimmer':      'shimmer 1.8s ease-in-out infinite',
        'status-ping':  'status-ping 1.8s cubic-bezier(0,0,0.2,1) infinite',
        'fade-up':      'fade-up 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      keyframes: {
        drift: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%':       { transform: 'translate(4%, -5%) scale(1.06)' },
          '50%':       { transform: 'translate(-3%, 4%) scale(0.97)' },
          '75%':       { transform: 'translate(3%, 2%) scale(1.04)' },
        },
        'drift-alt': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%':       { transform: 'translate(-5%, 3%) scale(1.08)' },
          '66%':       { transform: 'translate(4%, -4%) scale(0.94)' },
        },
        'spin-slow':    { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'spin-reverse': { from: { transform: 'rotate(360deg)' }, to: { transform: 'rotate(0deg)' } },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':       { transform: 'translateY(-8px)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 12px -2px var(--color-glow)', opacity: '0.7' },
          '50%':       { boxShadow: '0 0 28px 2px var(--color-glow)', opacity: '1' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-400% 0' },
          '100%': { backgroundPosition: '400% 0' },
        },
        'status-ping': {
          '0%':        { transform: 'scale(1)', opacity: '1' },
          '75%, 100%': { transform: 'scale(2.2)', opacity: '0' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
